export const villages = [
    {
        id: 1,
        title: "TraVival: Training for Travel Revival",
        description: "Creating a Travel Ecosystem for Planet Revival",
        shortDescription: "Creating a Travel Ecosystem for Planet Revival",
        image: "https://plus.unsplash.com/premium_photo-1661905195522-41da87e831d8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bmF0dXJlJTIwdmlsbGFnZXxlbnwwfHwwfHx8MA%3D%3D",
        location: "Spiti Valley, Himachal Pradesh",
        duration: "7 days",
        participants: 25,
        fullDescription:
            "TraVival is an innovative program designed to revolutionize sustainable travel practices in the pristine Spiti Valley. This comprehensive training focuses on creating eco-friendly travel ecosystems that benefit both visitors and local communities. Participants will learn about responsible tourism, environmental conservation, and community engagement while experiencing the breathtaking landscapes of one of India's most remote regions.",
        highlights: [
            "Sustainable tourism practices",
            "Community-based tourism development",
            "Environmental conservation techniques",
            "Cultural immersion experiences",
            "High-altitude ecosystem understanding",
        ],
        hosts: [
            {
                id: 1,
                name: "Tenzin Norbu",
                avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop&crop=face",
                role: "Local Guide",
            },
            {
                id: 2,
                name: "Priya Sharma",
                avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=60&h=60&fit=crop&crop=face",
                role: "Eco-Tourism Expert",
            },
            {
                id: 3,
                name: "Lobsang Tashi",
                avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop&crop=face",
                role: "Cultural Ambassador",
            },
            {
                id: 4,
                name: "Sarah Chen",
                avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&crop=face",
                role: "Sustainability Consultant",
                isNew: true,
            },
        ],
    },
    {
        id: 2,
        title: "Community Library & Storytelling Session",
        description: "For the inquisitive and book-loving kids of Chaminco Village, Himachal Pradesh.",
        shortDescription: "For the inquisitive and book-loving kids of Chaminco Village, Himachal Pradesh.",
        image: "https://media.istockphoto.com/id/514856110/photo/woman-working-on-the-rice-field.webp?a=1&b=1&s=612x612&w=0&k=20&c=nDOai8wFXpJn0ukBhwLwp0IeI3-p8CAbv4OgDS3W1sA=",
        location: "Chaminco Village, Himachal Pradesh",
        duration: "5 days",
        participants: 40,
        fullDescription:
            "The Community Library & Storytelling Session is a heartwarming initiative aimed at fostering a love for reading and storytelling among the children of Chaminco Village. This program combines traditional oral storytelling with modern library management, creating a sustainable knowledge-sharing ecosystem that will benefit generations to come.",
        highlights: [
            "Interactive storytelling sessions",
            "Library setup and management",
            "Reading skill development",
            "Cultural story preservation",
            "Community engagement activities",
        ],
        hosts: [
            {
                id: 5,
                name: "Kamala Devi",
                avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop&crop=face",
                role: "Village Elder",
            },
            {
                id: 6,
                name: "Raj Kumar",
                avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop&crop=face",
                role: "Teacher",
            },
            {
                id: 7,
                name: "Meera Thakur",
                avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=60&h=60&fit=crop&crop=face",
                role: "Librarian",
            },
            {
                id: 8,
                name: "Arjun Singh",
                avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=60&h=60&fit=crop&crop=face",
                role: "Storyteller",
                isNew: true,
            },
        ],
    },
    {
        id: 3,
        title: "Menstrual Health & Hygiene Drive",
        description: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        shortDescription: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        image: "https://images.unsplash.com/photo-1565655841161-64e40726df56?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cnVyYWwlMjB2aWxsYWdlcyUyMHRvdXJpc3QlMjBwbGFjZXxlbnwwfHwwfHx8MA%3D%3D",
        location: "Rural Maharashtra",
        duration: "3 days",
        participants: 60,
        fullDescription:
            "The Menstrual Health & Hygiene Drive is a crucial awareness program addressing menstrual health taboos and promoting proper hygiene practices in rural communities. This initiative combines education, distribution of hygiene products, and community dialogue to create lasting positive change in attitudes toward menstrual health.",
        highlights: [
            "Menstrual health education",
            "Hygiene product distribution",
            "Community awareness sessions",
            "Breaking social taboos",
            "Women empowerment workshops",
        ],
        hosts: [
            {
                id: 9,
                name: "Dr. Sunita Patil",
                avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=60&h=60&fit=crop&crop=face",
                role: "Health Expert",
            },
            {
                id: 10,
                name: "Rekha Joshi",
                avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=60&h=60&fit=crop&crop=face",
                role: "Social Worker",
            },
            {
                id: 11,
                name: "Anita Desai",
                avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=60&h=60&fit=crop&crop=face",
                role: "Community Leader",
            },
            {
                id: 12,
                name: "Pooja Mehta",
                avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=60&h=60&fit=crop&crop=face",
                role: "Health Educator",
                isNew: true,
            },
        ],
    },
    {
        id: 4,
        title: "Menstrual Health & Hygiene Drive",
        description: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        shortDescription: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        image: "https://images.unsplash.com/photo-1565655841161-64e40726df56?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cnVyYWwlMjB2aWxsYWdlcyUyMHRvdXJpc3QlMjBwbGFjZXxlbnwwfHwwfHx8MA%3D%3D",
        location: "Rural Maharashtra",
        duration: "3 days",
        participants: 60,
        fullDescription:
            "The Menstrual Health & Hygiene Drive is a crucial awareness program addressing menstrual health taboos and promoting proper hygiene practices in rural communities. This initiative combines education, distribution of hygiene products, and community dialogue to create lasting positive change in attitudes toward menstrual health.",
        highlights: [
            "Menstrual health education",
            "Hygiene product distribution",
            "Community awareness sessions",
            "Breaking social taboos",
            "Women empowerment workshops",
        ],
        hosts: [
            {
                id: 9,
                name: "Dr. Sunita Patil",
                avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=60&h=60&fit=crop&crop=face",
                role: "Health Expert",
            },
            {
                id: 10,
                name: "Rekha Joshi",
                avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=60&h=60&fit=crop&crop=face",
                role: "Social Worker",
            },
            {
                id: 11,
                name: "Anita Desai",
                avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=60&h=60&fit=crop&crop=face",
                role: "Community Leader",
            },
            {
                id: 12,
                name: "Pooja Mehta",
                avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=60&h=60&fit=crop&crop=face",
                role: "Health Educator",
                isNew: true,
            },
        ],
    },
    {
        id: 5,
        title: "Menstrual Health & Hygiene Drive",
        description: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        shortDescription: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        image: "https://images.unsplash.com/photo-1689428615940-64d549e2231c?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cnVyYWwlMjB2aWxsYWdlcyUyMHRvdXJpc3QlMjBwbGFjZXxlbnwwfHwwfHx8MA%3D%3D",
        location: "Rural Maharashtra",
        duration: "3 days",
        participants: 60,
        fullDescription:
            "The Menstrual Health & Hygiene Drive is a crucial awareness program addressing menstrual health taboos and promoting proper hygiene practices in rural communities. This initiative combines education, distribution of hygiene products, and community dialogue to create lasting positive change in attitudes toward menstrual health.",
        highlights: [
            "Menstrual health education",
            "Hygiene product distribution",
            "Community awareness sessions",
            "Breaking social taboos",
            "Women empowerment workshops",
        ],
        hosts: [
            {
                id: 9,
                name: "Dr. Sunita Patil",
                avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=60&h=60&fit=crop&crop=face",
                role: "Health Expert",
            },
            {
                id: 10,
                name: "Rekha Joshi",
                avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=60&h=60&fit=crop&crop=face",
                role: "Social Worker",
            },
            {
                id: 11,
                name: "Anita Desai",
                avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=60&h=60&fit=crop&crop=face",
                role: "Community Leader",
            },
            {
                id: 12,
                name: "Pooja Mehta",
                avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=60&h=60&fit=crop&crop=face",
                role: "Health Educator",
                isNew: true,
            },
        ],
    },
    {
        id: 6,
        title: "Menstrual Health & Hygiene Drive",
        description: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        shortDescription: "An attempt to become more sensitive and bolder towards the issue of Menstrual Health.",
        image: "https://plus.unsplash.com/premium_photo-1726313836345-3524772937fe?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cnVyYWwlMjB2aWxsYWdlcyUyMHRvdXJpc3QlMjBwbGFjZXxlbnwwfHwwfHx8MA%3D%3D",
        location: "Rural Maharashtra",
        duration: "3 days",
        participants: 60,
        fullDescription:
            "The Menstrual Health & Hygiene Drive is a crucial awareness program addressing menstrual health taboos and promoting proper hygiene practices in rural communities. This initiative combines education, distribution of hygiene products, and community dialogue to create lasting positive change in attitudes toward menstrual health.",
        highlights: [
            "Menstrual health education",
            "Hygiene product distribution",
            "Community awareness sessions",
            "Breaking social taboos",
            "Women empowerment workshops",
        ],
        hosts: [
            {
                id: 9,
                name: "Dr. Sunita Patil",
                avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=60&h=60&fit=crop&crop=face",
                role: "Health Expert",
            },
            {
                id: 10,
                name: "Rekha Joshi",
                avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=60&h=60&fit=crop&crop=face",
                role: "Social Worker",
            },
            {
                id: 11,
                name: "Anita Desai",
                avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=60&h=60&fit=crop&crop=face",
                role: "Community Leader",
            },
            {
                id: 12,
                name: "Pooja Mehta",
                avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=60&h=60&fit=crop&crop=face",
                role: "Health Educator",
                isNew: true,
            },
        ],
    },
]